title : Ideas API

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: api-ideas
destination: api-ideas

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 1000
paginate_path: "/blog/page:num"

production_url : http://ideas.apievangelist.com

BASE_PATH : http://ideas.apievangelist.com

categories_path : /categories.html
tags_path : /tags.html
