title : Image Manipulation API

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: image-manipulation
destination: image-manpulation

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 1000
paginate_path: "/blog/page:num"

production_url : http://image.manipulation.apievangelist.com

BASE_PATH : http://image.manipulation.apievangelist.com

categories_path : /categories.html
tags_path : /tags.html
